version: "3"

services:
  pdfsort:
    image: ${IMAGE_REPO_NAME}
    build:
      context: .
      dockerfile: ./docker/pdf/Dockerfile
    container_name: myWork-pdf
    env_file:
      - ./docker/pdf/pdf.env
    environment:
      S3_BUCKET_NAME: mywork-web-bucket
      LOG_LEVEL: DEBUG
    volumes:
      - ./app:/opt/app
      - ./docker/pdf/file:/tmp

